class DatagramSocket:
    def __init__(self, lip, lport, rip, rport): ...

    def recieve(self, n, timeout) -> list[int]: ...
    def transmit(self, buf): ...

class Socket:
    def __init__(self, lip, lport, rip, rport): ...
    def __init__(self, socket): ...

    def recieve(): ...
    def transmit(): ...

class Server:
    def __init__(self, ip, port): ...

    def accept(self) -> Socket: ...

